### PR TITLE
Clean up CrateView classes

### PR DESCRIPTION
**Pull request by SubtypeZero**
I felt that the CrateView classes were a little messy, so I spent a few hours looking over them and taking some time to clean them up a bit. I still think classes in the crate view package can be cleaned up a little more, but this should help make them a little more readable.

Changes:
- Changed CrateView to be abstract
- Added basic inventory building method to CrateView (based on how they were being made previously), which is called in CrateView's constructor, though some views are somewhat special and don't use this method (they create their own inventories).
- Moved updater into CrateView, which is now started by calling startUpdateTask()
- Added openInventory method (currently unused, but perhaps useful)
- Renamed updateInv(state) to updateView(state)
- Moved getInventory() to CrateView, special cases can override

Most files changed are in src/main/java/com/codehusky/huskycrates/crate/views

I have not extensively tested the changes, though I don't believe that any of the core logic has been changed, so no functionality should be broken.

### CODE REVIEW

**Comment by codeHusky** [comment]
Will test asap

**Comment by SubtypeZero** [comment]
Looks like there's an NPE that needs to be investigated, I fixed one of them but there's a new one here:
[SpinnerCrateView.java#L85](https://github.com/SubtypeZero/HuskyCrates-Sponge/blob/67b116ac518a48b1bd66dd473d8eea86dd1a93cf/src/main/java/com/codehusky/huskycrates/crate/views/SpinnerCrateView.java#L85)

It looks like there might be an issue loading in the item set from VirtualCrate, but I haven't been able to find it yet.

**Comment by SubtypeZero** [comment]
Have you taken some time to test these changes?

**Comment by codeHusky** [comment]
alright, i'll actually look at this tonight if i get the chance, sorry for the delay :sweat:

**Comment by codeHusky** [comment]
ill be merging this tomorrow with a proper diff tool because github's online thing is terrible.

**Comment by codeHusky** [comment]
Would you mind moving this to the latest commit before I merge?

**Comment by SubtypeZero** [comment]
Anything else?

**Comment by SubtypeZero** [comment]
I didn't realize I had reformatted with tabs, so the spaces are back.

**Comment by codeHusky** [comment]
It's too late to consider merging this for me rn. I'll just clean them up later, sorry for the inconvenience.

**Pull request closed without merging**
