### PR TITLE
Refactor particle patterns out through an interface

### PR DESCRIPTION
**Pull request by pie-flavor**

### CODE REVIEW

**Comment by codeHusky** [comment]
Going to build this and test, see if theres any new bugs or anything (or if performance improves/degrades) and get back to you

**Comment by codeHusky** [comment]
This PR throws errors when the crate doesn't have any particles configured.

**Comment by pie-flavor** [comment]
A crate with no particles configured wouldn't use any class that's been touched by this PR. What do the errors look like?

**Comment by codeHusky** [comment]
The error has to do with the particlepattern being null if there's no specified particle effects in the config.

It's getting fired during the scheduler cycle. 

I'll let you know specifically once I can test again

**Comment by codeHusky** [comment]
closing this since i'll be doing this some othjer time.

**Pull request closed without merging**
